Grafana upgrade 3.0.4
Dashboards *system-metrics.json* and *welcome.json* were removed because they cause an error when loaded

**UI**
```
Dashboard init failed
Template variables could not be initialized: b.metricFindQuery is not a function
```

**JS Console**

```
TypeError: b.metricFindQuery is not a function
    at updateOptionsFromMetricFindQuery (boot.16792590.js:10)
    at b (boot.16792590.js:40)
    at h (boot.16792590.js:35)
    at boot.16792590.js:35
    at n.$eval (boot.16792590.js:35)
    at n.$digest (boot.16792590.js:35)
    at boot.16792590.js:35
    at e (boot.16792590.js:34)
    at boot.16792590.js:34
```

Dashboard *docker.json* was modified by removing id. Client cannot provide an id when POST-ing a new dashboard - there is rather unhelpful error message

```
HTTP/1.1 404 Not Found
{"message":"Dashboard not found","status":"not-found"}
```